---
version: "3"
services:
  test:
    build:
      context: .
      target: requirements
    user: ${USERGROUP:?}
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: true
    environment:
      HOME: /tmp
      PYTHONPATH: /app/src
    entrypoint:
      - timeout
      - "60"
      - bash
      - ./tests/run_in_docker.sh

  test_full:
    build:
      context: .
      target: app
    entrypoint:
      - timeout
      - "60"
      - bash
      - ./tests/run_in_docker.sh

  shell:
    build:
      context: .
      target: requirements
    user: ${USERGROUP:?}
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: false
      - type: bind
        source: ./build
        target: /build
        read_only: false
    environment:
      HOME: /tmp
      PYTHONPATH: /app/src:/app
      HISTFILE: /build/.bash_history
      PROMPT_COMMAND: history -a
    entrypoint:
      - bash
      - -leuc
      - |
        export PATH=/tmp/.local/bin:$$PATH &&
        /app/tests/start_nomad_server.sh &&
        # pip install -e .[test]
        exec "$${@:-bash}"
      - --
