---
repos:
  # - Kamilcuk
  - Kamilcuk/nomad-tools
  - Kamilcuk/runnertest
  - Kamilcuk/builder
nomad:
  namespace: github
  # purge: false
  # purge: true
runner_inactivity_timeout: 1w
loop: 10
# loop: 60
template_settings:
  # docker: host
  docker: dind
  cachedir: /home/kamil/myprojects/nomad-tools/deploy/cachedir

