---
loop: 10
# loop: 60

repos:
  # - Kamilcuk
  - Kamilcuk/nomad-tools
  - Kamilcuk/runnertest
  - Kamilcuk/builder
  - Kamilcuk/ckd
  - Kamilcuk/kamilscripts
nomad:
  namespace: github
  # purge: false
  # purge: true
template_settings:
  # docker: host
  docker: dind
  ephemeral: false
scheduler:
  runner_inactivity_timeout: 1w
